name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t layout_editor_linux:latest -f linux/Dockerfile .

      - name: Run Docker container
        run: |
          docker run --name layout_editor_container layout_editor_linux:latest
          docker cp layout_editor_container:/usr/src/app/dist linux/dist
          docker rm layout_editor_container

      - name: Create tar.gz of Linux build artifact
        run: tar -czf linux-dist.tar.gz -C dist .

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-dist
          path: linux-dist.tar.gz

  build-windows:
    name: Build on Windows
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.12'

      - name: Install dependencies
        run: |
          cd windows
          pip install -r requirements.txt

      - name: Build distribution
        run: |
          cd windows
          python setup.py sdist bdist_wheel

      - name: Create release asset
        run: |
          cd windows/dist
          tar -czf windows-dist.tar.gz *

      - name: Upload release asset
        uses: actions/upload-artifact@v2
        with:
          name: windows-dist
          path: windows/dist/windows-dist.tar.gz

  create-release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Linux build artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-dist
          path: ./dist/linux

      - name: Download Windows build artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-dist
          path: ./dist/windows

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Release for commit ${{ github.sha }}.
          draft: false
          prerelease: false

      - name: Upload Linux artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/linux/linux-dist.tar.gz
          asset_name: linux-dist.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows/windows-dist.tar.gz
          asset_name: windows-dist.tar.gz
          asset_content_type: application/gzip
