name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd linux
          docker build -t layout_editor_linux -f Dockerfile .
          cd ..

      - name: Run Docker container
        run: |
          docker run --name layout_editor_container layout_editor_linux
          docker cp layout_editor_container:/usr/src/app/dist linux/dist
          docker rm layout_editor_container

      - name: List Linux dist directory
        run: ls -la linux/dist

      - name: Create a new tag
        id: create_tag_linux
        run: |
          TAG_NAME="v1.0-linux-$(date +%s)"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create GitHub Release for Linux
        id: create_release_linux
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: |
            Release for commit ${{ github.sha }} (Linux).
          files: |
            linux/dist/*.tar.gz
            linux/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          pip install wheel
          cd windows
          python setup.py sdist bdist_wheel

      - name: Create a new tag
        id: create_tag_windows
        shell: pwsh
        run: |
          $TAG_NAME="v1.0-windows-$(Get-Date -UFormat %s)"
          echo "TAG_NAME=$TAG_NAME" >> $env:GITHUB_ENV

      - name: Create GitHub Release for Windows
        id: create_release_windows
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: |
            Release for commit ${{ github.sha }} (Windows).
          files: |
            windows/dist/*.tar.gz
            windows/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
